### ISSUE TITLE
HRD Support for AD Connectors 

### ISSUE THREAD

**Issue by pose** [auth0/lock#13]
_WIP_ 

The user story will be:
1. User writes their email.
2. While the user press enter or clicks on signin, we search throughout the connections if there is one of them registered with the email suffix and its type is AD Connector (for instance, `@mydomain.com`).
3. lock launches new mode (`adldap`) (or shall we re-use `signin` mode @cristiandouce ?)
4. This new state has `username` instead of email and it can write the password there. The new screen has not forgotten email or signup. Only a cancel button to go to the previous state.
5. When they enter the credentials and clicks on `access` it should use the selected `ad/ldap` connection sending `username` and `password`. There should not be a redirect as it happens today. It should work as a DB connection.

---
- [x]  Try with an enterprise connection.
- [x] ~~Implement escape key to leave HRD.~~ No escape for now.
- [x] What happens if my domain is really large?
  - [x] https://github.com/auth0/lock/issues/25
  - [x] add to `tittle` field of the access button the full domain name.
  - [x] add `overflow` and `text-overflow` (for ellipsis)
- [x] Implement new UI (as shown in #lock)
- [x] ~~show top label when there is only one ad connection.~~ This is error prone as the connection may have multiple domain aliases. Not doing for now.
- [x] Code Cleanup

---
### tasks
- [x] widget login ready?
- [x] documented?
- [x] updated widget docs
  - [x]  [[1]](https://github.com/auth0/lock/wiki/Auth0Lock-customization#defaultuserpasswordconnection-string)
- [x] ~~updated auth0-configuration~~ No lock yet.
- [x] ~~updated auth0-vagrant~~ No lock yet.
- [x] Contacted people who wanted that feature
